<?php

namespace WebsiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        $instance = new \WebsiteBundle\Controller\DefaultController($container->get('solrservice', 1), $container->get('templating', 1));
        return $instance;
    }
}
